app:
  title: Scaffolded Backstage App
  baseUrl: http://localhost:3000
  experimental:
    packages: all
organization:
  name: My Company

backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007
  csp:
    connect-src: ["'self'", 'http:', 'https:']
  cors:
    origin: http://localhost:3000
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  database:
    client: pg
    connection:
      host: 'localhost'
      port: '5432'
      user: 'postgres'
      password: '1234'

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}

proxy:
  # Example proxy endpoint configuration
  # endpoints:
  #   '/test':
  #     target: 'https://example.com'
  #     changeOrigin: true

techdocs:
  builder: 'local'
  generator:
    runIn: 'docker'
  publisher:
    type: 'local'

# auth:
#   environment: development
#   session:
#     secret: SHZ2/jKybsW1tPrsWndJMDEeOHzYYDiBcBjqgcTBoPQ=
#   providers:
#     keycloak:
#       development:
#         clientId: Backstage_Keycloak
#         clientSecret: X9jjURan8exVip4jacDHRRLNf3MJU3Cp
#         # issuer: 'http://localhost:8080/realms/BackStage'
#         metadataUrl: 'http://localhost:8080/realms/BackStage/.well-known/openid-configuration'
#         # authUrl: 'http://localhost:8080/realms/BackStage/protocol/openid-connect/auth'
#         # tokenUrl: 'http://localhost:8080/auth/realms/BackStage/protocol/openid-connect/token'
#         # scope: 'openid'
#         redirectUri: http://localhost:7007/api/auth/keycloak/handler/frame
#         # signIn:
#         #   resolvers:
#         #     - resolver: usernameMatchingUserEntityName

scaffolder:
  # Software template options configuration

catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location]
  locations:
    - type: file
      target: ../../examples/entities.yaml
    - type: file
      target: ../../examples/template/template.yaml
      rules:
        - allow: [Template]
    - type: file
      target: ../../examples/org.yaml
      rules:
        - allow: [User, Group]

kubernetes:
  # Kubernetes configuration options

permission:
  enabled: true
